import { useCallback } from "react";
import { useToast } from "@/hooks/use-toast";
import { NarrativeItem, ResponseLetter } from "@/lib/resultsPersistence";

const narrativeTypeLabels: Record<string, string> = {
  full_disclosure: "Direct & Professional",
  skills_focused: "Skills-First Approach",
  growth_journey: "Growth-Focused",
  minimal_disclosure: "Brief & Confident",
  values_aligned: "Values-Aligned",
};

export function useDocumentActions() {
  const { toast } = useToast();

  const copyToClipboard = useCallback(async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast({
        title: "Copied to clipboard",
        description: `${label} has been copied to your clipboard.`,
      });
      return true;
    } catch (err) {
      toast({
        title: "Failed to copy",
        description: "Please try selecting and copying the text manually.",
        variant: "destructive",
      });
      return false;
    }
  }, [toast]);

  const downloadFile = useCallback((content: string, filename: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Download started",
      description: `${filename} is being downloaded.`,
    });
  }, [toast]);

  const handleCopyNarrative = useCallback((narrative: NarrativeItem) => {
    const label = narrative.title || narrativeTypeLabels[narrative.type] || "Narrative";
    return copyToClipboard(narrative.content, label);
  }, [copyToClipboard]);

  const handleCopyLetter = useCallback((letter: ResponseLetter) => {
    return copyToClipboard(letter.content, "Response Letter");
  }, [copyToClipboard]);

  const handleDownloadNarrative = useCallback((narrative: NarrativeItem) => {
    const label = narrative.title || narrativeTypeLabels[narrative.type] || "Narrative";
    let content = `${label.toUpperCase()}\n`;
    content += "Generated by ReflectMe\n";
    content += "=".repeat(50) + "\n\n";
    content += narrative.content;

    const filename = `narrative-${narrative.type}.txt`;
    downloadFile(content, filename);
  }, [downloadFile]);

  const handleDownloadLetter = useCallback((letter: ResponseLetter) => {
    let content = "PRE-ADVERSE ACTION RESPONSE LETTER\n";
    content += "Generated by ReflectMe\n";
    content += "=".repeat(50) + "\n\n";
    content += letter.content;

    downloadFile(content, "response-letter.txt");
  }, [downloadFile]);

  const handleDownloadAllNarratives = useCallback((narratives: NarrativeItem[]) => {
    if (narratives.length === 0) return;

    let content = "DISCLOSURE NARRATIVES\n";
    content += "Generated by ReflectMe\n";
    content += "=".repeat(50) + "\n\n";

    narratives.forEach((narrative, index) => {
      const label = narrative.title || narrativeTypeLabels[narrative.type] || `Narrative ${index + 1}`;
      content += `${index + 1}. ${label}\n`;
      content += "-".repeat(40) + "\n\n";
      content += narrative.content + "\n\n";
      content += "=".repeat(50) + "\n\n";
    });

    downloadFile(content, "disclosure-narratives.txt");
  }, [downloadFile]);

  const handleDownloadAll = useCallback((narratives: NarrativeItem[], letter: ResponseLetter | null) => {
    let content = "REFLECTME DOCUMENTS\n";
    content += "=".repeat(50) + "\n\n";

    if (narratives.length > 0) {
      content += "DISCLOSURE NARRATIVES\n";
      content += "-".repeat(40) + "\n\n";

      narratives.forEach((narrative, index) => {
        const label = narrative.title || narrativeTypeLabels[narrative.type] || `Narrative ${index + 1}`;
        content += `${index + 1}. ${label}\n`;
        content += narrative.content + "\n\n";
      });

      content += "=".repeat(50) + "\n\n";
    }

    if (letter) {
      content += "PRE-ADVERSE ACTION RESPONSE LETTER\n";
      content += "-".repeat(40) + "\n\n";
      content += letter.content + "\n";
    }

    downloadFile(content, "reflectme-documents.txt");
  }, [downloadFile]);

  return {
    copyToClipboard,
    handleCopyNarrative,
    handleCopyLetter,
    handleDownloadNarrative,
    handleDownloadLetter,
    handleDownloadAllNarratives,
    handleDownloadAll,
    narrativeTypeLabels,
  };
}
